name: Build and Deploy Hexo
on:
  push:
    branches:
      - hexo
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      
    - name: Use Node.js 12
      uses: actions/setup-node@v3
      with:
        node-version: '12'

    - name: Install Pandoc
      run: |
        sudo apt-get install pandoc
        
    - name: Install and Build 🔧 
      run: |
        npm install -g hexo-cli
        npm install
        hexo clean
        hexo generate

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public